(in-package :cl-user)

(defpackage :webkit
  (:use :cl :cffi)
  (:export
   #:webkit-web-view-get-type
   #:webkit-web-view-new
   #:webkit-web-view-get-title
   #:webkit-web-view-get-uri
   #:webkit-web-view-set-maintains-back-forward-list
   #:webkit-web-view-get-back-forward-list
   #:webkit-web-view-go-to-back-forward-item
   #:webkit-web-view-can-go-back
   #:webkit-web-view-can-go-back-or-forward
   #:webkit-web-view-can-go-forward
   #:webkit-web-view-go-forward
   #:webkit-web-view-stop-loading
   #:webkit-web-view-open
   #:webkit-web-view-reload
   #:webkit-web-view-reload-bypass-cache
   #:webkit-web-view-load-uri
   #:webkit-web-view-load-string
   #:webkit-web-view-load-html-string
   #:webkit-web-view-load-request
   #:webkit-web-view-search-text
   #:webkit-web-view-mark-text-matches
   #:webkit-web-view-set-highlight-text-matches
   #:webkit-web-view-unmark-text-matches
   #:webkit-web-view-get-main-frame
   #:webkit-web-view-get-focused-frame
   #:webkit-web-view-execute-script
   #:webkit-web-view-can-cut-clipboard
   #:webkit-web-view-can-copy-clipboard
   #:webkit-web-view-can-paste-clipboard
   #:webkit-web-view-cut-clipboard
   #:webkit-web-view-copy-clipboard
   #:webkit-web-view-paste-clipboard
   #:webkit-web-view-delete-selection
   #:webkit-web-view-has-selection
   #:webkit-web-view-select-all
   #:webkit-web-view-get-editable
   #:webkit-web-view-set-editable
   #:webkit-web-view-get-copy-target-list
   #:webkit-web-view-get-paste-target-list
   #:webkit-web-view-set-settings
   #:webkit-web-view-get-settings
   #:webkit-web-view-get-inspector
   #:webkit-web-view-get-window-features
   #:wekbit-web-view-can-show-mime-type
   #:webkit-web-view-get-transparent
   #:webkit-web-view-get-zoom-level
   #:webkit-web-view-set-zoom-level
   #:webkit-web-view-zoom-in
   #:webkit-web-view-zoom-out
   #:webkit-web-view-get-full-content-zoom
   #:webkit-web-view-set-full-content-zoom
   #:webkit-get-default-session
   #:webkit-web-view-get-encoding
   #:webkit-web-view-set-custom-encoding
   #:webkit-web-view-move-cursor
   #:webkit-web-view-get-load-status
   #:webkit-web-view-get-progress
   #:webkit-web-view-undo
   #:webkit-web-view-can-undo
   #:webkit-web-view-redo
   #:webkit-web-view-can-redo
   #:webkit-web-view-set-view-source-mode
   #:webkit-web-view-get-view-source-mode
   #:webkit-web-view-get-hit-test-result
   #:webkit-web-view-get-icon-uri
   #:webkit-set-cache-model
   #:webkit-get-cache-model))
