#!/bin/sh
#
# Pre-commit checks

LISP="sbcl --noinform --no-userinit"
topdir=$(git rev-parse --show-toplevel)
run_build_test=false

cd "$topdir"
for x in $(git diff-index --cached --name-only HEAD) ; do
    case "$x" in
        scripts/*) continue ;;
        *.lisp|*.asd) run_build_test=true ;;
    esac
done

if $run_build_test ; then
    echo "Running build test" >&2
    $LISP --load scripts/buildtest.lisp --eval '(buildtest :cl-webkit2)' >&2
    if [ $? -ne 0 ] ; then
        echo "Commit rejected: build failed" >&2
        exit 1
    fi
fi
