#!/bin/sh
#
# Pre-commit checks

LISP="sbcl --noinform --no-userinit"
topdir=$(git rev-parse --show-toplevel)
run_test_suite=false

cd "$topdir"
for x in $(git diff-index --cached --name-only HEAD) ; do
    case "$x" in
        scripts/*) continue ;;
        *.lisp|*.asd) run_test_suite=true ;;
    esac
done

if $run_test_suite ; then
    echo "Running test-suite" >&2
    $LISP --load scripts/run-tests.lisp >&2
    if [ $? -ne 0 ] ; then
        echo "Commit rejected: test-suite failed" >&2
        exit 1
    fi
fi
